version: 2
hourly:
    triggers:
        - schedule: null
            cron: '0 * * * *'
jobs:
    build:
        docker:
            - {image: 'circleci/node:10.14-browsers'}
        working_directory: ~/hiring_test
        steps:
            - checkout
            - {restore_cache: {keys: ['v1-dependencies-{{ checksum "package.json" }}', v1-dependencies-]}}
            - {run: 'yarn install'}
            - {save_cache: {paths: [node_modules], key: 'v1-dependencies-{{ checksum "package.json" }}'}}
            - {run: 'yarn test'}
            - {store_test_results: {path: /tmp/test-results}}
